[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/fts"
  to = "/.netlify/functions/fts"
  status = 200

[[redirects]]
  from = "/mobile"
  to = "/mobile/mobile.html"
  status = 200
